name: Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # 毎日自動ビルドする場合

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Qt
        uses: jurplel/install-qt-action@v4

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

